import One from "public/img/project/01.jpg";
import Two from "public/img/project/02.jpg";
import Three from "public/img/project/03.jpg";
import Four from "public/img/project/04.jpg";
import Five from "public/img/project/05.jpg";
import Six from "public/img/project/06.jpg";

const ProjectGalleryData = [
  {
    id: 0,
    img: One,
    titl: "Analys & Backup Blockchain",
    des: "Safeguard your blockchain investment with our Analysis & Backup Blockchain service. We provide comprehensive analysis to ensure the integrity of your blockchain, coupled with robust backup solutions. Your data and transactions remain secure, allowing you to navigate the blockchain landscape with confidence.",
    path1: "/",
    path2: "/",
    path3: "/",
    links1: "Backup",
    links2: "Data",
    links3: "Backup",
    category: "data",
    area: "Data Security",
  },
  {
    id: 1,
    img: Two,
    titl: "Rento Car Rental Dashboard",
    des: "Elevate your car rental business with our Rento Car Rental Dashboard service. Tailored specifically for your industry, our dashboard enhances operational efficiency, offering a centralized platform for reservations, fleet management, and customer interactions. Drive success in your car rental venture with a seamlessly integrated dashboard solution.",
    path1: "/",
    path2: "/",
    path3: "/",
    links1: "Backup",
    links2: "Data",
    links3: "Backup",
    category: "game",
    area: "Game Development",
  },
  {
    id: 2,
    img: Three,
    titl: "Creative Landing Page Service",
    des: "Make a lasting impression online with our Creative Landing Page Service. Our expert team crafts visually stunning and strategically designed landing pages that captivate visitors and drive conversions. Maximize the impact of your online presence with engaging landing pages tailored to your brand and business goals.",
    path1: "/",
    path2: "/",
    path3: "/",
    links1: "Backup",
    links2: "Data",
    links3: "Backup",
    category: "it",
    area: "It Consultation",
  },
  {
    id: 3,
    img: Four,
    titl: "Infrastructure Upgrade",
    des: "Propel your business forward with our Infrastructure Upgrade service. Stay ahead of technological advancements by enhancing your infrastructure for optimal performance, scalability, and security. Future-proof your operations and ensure a seamless digital experience for your users.",
    path1: "/",
    path2: "/",
    path3: "/",
    links1: "Backup",
    links2: "Data",
    links3: "Backup",
    category: "seo",
    area: "SEO",
  },
  {
    id: 4,
    img: Five,
    titl: "AR/VR War 1986 Game",
    des: "Immerse your audience in the future of gaming with our AR/VR War 1986 Game service. Harness the power of augmented and virtual reality to create an interactive and thrilling gaming experience. Our expertise in AR/VR technology ensures a game that goes beyond entertainment, providing an immersive and unforgettable adventure.",
    path1: "/",
    path2: "/",
    path3: "/",
    links1: "Backup",
    links2: "Data",
    links3: "Backup",
    category: "data",
    area: "Data Security",
  },
  {
    id: 5,
    img: Six,
    titl: "Rento Car Rental Dashboard",
    des: "Optimize your car rental business with our Rento Car Rental Dashboard service. From efficient reservation management to streamlined fleet oversight, our tailored dashboard solution is designed to enhance your operational prowess. Elevate customer satisfaction and drive business success with a centralized platform that puts you in control of reservations, customer interactions, and fleet management.",
    path1: "/",
    path2: "/",
    path3: "/",
    links1: "Backup",
    links2: "Data",
    links3: "Backup",
    category: "game",
    area: "Game Development",
  },
];

export default ProjectGalleryData;
